name: Release Firefox Extension
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v4
      - run: |
          npm install
          ./bin/prepare-firefox.sh ${{ github.ref_name }}
      - run: |
          echo "npx web-ext sign --channel listed --source-dir dist-firefox --artifacts-dir ."
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
